#!/bin/bash
#SBATCH --job-name=kbcount_2C
#SBATCH -c 16
#SBATCH -t 01-00:00
#SBATCH -p sapphire
#SBATCH --mem=500G
#SBATCH --output=kbcount_2C_%j.out
#SBATCH --error=kbcount_2C_%j.err

# Activate your conda environment
source activate scanpy_env


# Directory containing the FASTQs
FASTQ_DIR="../data/2C"

# Where you want to place the output of kb count for each sample
OUTPUT_DIR="../output/kb_count/2C"

# Reference paths generated by kb ref
INDEX="../output/kb_ref/index.idx"
T2G="../output/kb_ref/t2g.tsv"

# List the sample “stubs” that uniquely identify each sample in your filenames
# (the part between "PREP0290_DPayz15138_" and "_L004_R1_001.fastq.gz")
SAMPLES=(
  "A9v1_Intact-2N-1_S1"
  "B9v1_Contra-2N-1_S2"
  "C9v1_Intact-2N-2_S3"
  "D9v1_Contra-2N-2_S4"
  "E9v1_Intact-2N-4_S5"
  "F9v1_Contra-2N-4_S6"
  "G9v1_Intact-2N-5_S7"
  "H9v1_Contra-2N-5_S8"
)

# Loop through each sample stub
for SAMPLE in "${SAMPLES[@]}"; do
    # Create full path to R1 and R2 for this sample
    R1="${FASTQ_DIR}/PREP0290_DPayz15138_${SAMPLE}_L004_R1_001.fastq.gz"
    R2="${FASTQ_DIR}/PREP0290_DPayz15138_${SAMPLE}_L004_R2_001.fastq.gz"

    # Create an output directory for each sample
    OUTDIR="${OUTPUT_DIR}/kb_count_${SAMPLE}"
    mkdir -p "${OUTDIR}"

    echo "Running kb count for sample: ${SAMPLE}"

    kb count \
      -i "${INDEX}" \
      -g "${T2G}" \
      -x 10xv3 \
      -o "${OUTDIR}" \
      --h5ad \
      -t 16 \
      "${R1}" "${R2}"
done
