#!/bin/bash
#SBATCH --job-name=2.2_kbcount_4C
#SBATCH -c 16
#SBATCH -t 01-00:00
#SBATCH -p sapphire
#SBATCH --mem=500G
#SBATCH --output=../log/2.2_kbcount_4C_%j.out
#SBATCH --error=../log/2.2_kbcount_4C_%j.err


# Activate your environment
source activate scanpy_env

# Directory containing the FASTQs (4C)
FASTQ_DIR="../data/4C"

# Where you want to place the output of kb count for each sample
OUTPUT_DIR="../output/kb_count/4C"

# Reference paths generated by kb ref
INDEX="../output/kb_ref/index.idx"
T2G="../output/kb_ref/t2g.tsv"

# List the 4C sample “stubs” (the part between 
# "PREP0203_DPayz13538A_" and "_L001_R1_001.fastq.gz")
SAMPLES=(
  "A8v1_Intact-4N-1_S1"
  "B8v1_Intact-4N-3_S2"
  "C8v1_Intact-4N-4_S3"
  "D8v1_Intact-4N-5_S4"
  "E8v1_Contra-4N-1_S5"
  "F8v1_Contra-4N-2_S6"
  "G8v1_Contra-4N-3_S7"
  "H8v1_Contra-4N-5_S8"
)

# Loop through each sample stub
for SAMPLE in "${SAMPLES[@]}"; do
    # Create full path to R1 and R2 for this sample
    R1="${FASTQ_DIR}/PREP0203_DPayz13538A_${SAMPLE}_L001_R1_001.fastq.gz"
    R2="${FASTQ_DIR}/PREP0203_DPayz13538A_${SAMPLE}_L001_R2_001.fastq.gz"

    # Create an output directory for each sample
    OUTDIR="${OUTPUT_DIR}/kb_count_${SAMPLE}"
    mkdir -p "${OUTDIR}"

    echo "Running kb count for sample: ${SAMPLE}"

    kb count \
      -i "${INDEX}" \
      -g "${T2G}" \
      -x 10xv3 \
      -o "${OUTDIR}" \
      --h5ad \
      -t 16 \
      "${R1}" "${R2}"
done